spring:
  application:
    name: smartmerge
  profiles:
    active: dev
  config:
    import: optional:classpath:application-secrets.yml
  # old way of dealing with jackson class casting exceptions (code will crash at runtime if enabled)
  # jackson:
  #   deserialization:
  #     use-long-for-ints: true
  ai:
    openai:
      api-key: ${openai.api-key}
      chat:
        options:
          model: gpt-4o
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${gitHubClientId}
            client-secret: ${gitHubClientSecret}
            scope:
              - read:user
              - user:email
  datasource:
    url: ${smartmerge.db.url}
    username: ${smartmerge.db.username}
    password: ${smartmerge.db.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

client:
  url: "http://localhost:5173"

jwt:
  secret.key: ${jwtSecret}

server:
  port: ${PORT:8081}

github:
  appId: ${github.appId}
  keyPath: ${github.key}
